/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RAuthenticatedRouteImport } from './routes/r/_authenticated'
import { Route as RAuthenticatedSidebarRouteImport } from './routes/r/_authenticated/_sidebar'
import { Route as RAuthenticatedSidebarResumesIndexRouteImport } from './routes/r/_authenticated/_sidebar/resumes/index'
import { Route as RAuthenticatedSidebarJobsIndexRouteImport } from './routes/r/_authenticated/_sidebar/jobs/index'
import { Route as RAuthenticatedSidebarDashboardIndexRouteImport } from './routes/r/_authenticated/_sidebar/dashboard/index'
import { Route as RAuthenticatedSidebarResumesResume_idIndexRouteImport } from './routes/r/_authenticated/_sidebar/resumes/$resume_id/index'
import { Route as RAuthenticatedSidebarJobsJob_idIndexRouteImport } from './routes/r/_authenticated/_sidebar/jobs/$job_id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RAuthenticatedRoute = RAuthenticatedRouteImport.update({
  id: '/r/_authenticated',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const RAuthenticatedSidebarRoute = RAuthenticatedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => RAuthenticatedRoute,
} as any)
const RAuthenticatedSidebarResumesIndexRoute =
  RAuthenticatedSidebarResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => RAuthenticatedSidebarRoute,
  } as any)
const RAuthenticatedSidebarJobsIndexRoute =
  RAuthenticatedSidebarJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => RAuthenticatedSidebarRoute,
  } as any)
const RAuthenticatedSidebarDashboardIndexRoute =
  RAuthenticatedSidebarDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => RAuthenticatedSidebarRoute,
  } as any)
const RAuthenticatedSidebarResumesResume_idIndexRoute =
  RAuthenticatedSidebarResumesResume_idIndexRouteImport.update({
    id: '/resumes/$resume_id/',
    path: '/resumes/$resume_id/',
    getParentRoute: () => RAuthenticatedSidebarRoute,
  } as any)
const RAuthenticatedSidebarJobsJob_idIndexRoute =
  RAuthenticatedSidebarJobsJob_idIndexRouteImport.update({
    id: '/jobs/$job_id/',
    path: '/jobs/$job_id/',
    getParentRoute: () => RAuthenticatedSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r': typeof RAuthenticatedSidebarRouteWithChildren
  '/r/dashboard/': typeof RAuthenticatedSidebarDashboardIndexRoute
  '/r/jobs/': typeof RAuthenticatedSidebarJobsIndexRoute
  '/r/resumes/': typeof RAuthenticatedSidebarResumesIndexRoute
  '/r/jobs/$job_id/': typeof RAuthenticatedSidebarJobsJob_idIndexRoute
  '/r/resumes/$resume_id/': typeof RAuthenticatedSidebarResumesResume_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r': typeof RAuthenticatedSidebarRouteWithChildren
  '/r/dashboard': typeof RAuthenticatedSidebarDashboardIndexRoute
  '/r/jobs': typeof RAuthenticatedSidebarJobsIndexRoute
  '/r/resumes': typeof RAuthenticatedSidebarResumesIndexRoute
  '/r/jobs/$job_id': typeof RAuthenticatedSidebarJobsJob_idIndexRoute
  '/r/resumes/$resume_id': typeof RAuthenticatedSidebarResumesResume_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/_authenticated': typeof RAuthenticatedRouteWithChildren
  '/r/_authenticated/_sidebar': typeof RAuthenticatedSidebarRouteWithChildren
  '/r/_authenticated/_sidebar/dashboard/': typeof RAuthenticatedSidebarDashboardIndexRoute
  '/r/_authenticated/_sidebar/jobs/': typeof RAuthenticatedSidebarJobsIndexRoute
  '/r/_authenticated/_sidebar/resumes/': typeof RAuthenticatedSidebarResumesIndexRoute
  '/r/_authenticated/_sidebar/jobs/$job_id/': typeof RAuthenticatedSidebarJobsJob_idIndexRoute
  '/r/_authenticated/_sidebar/resumes/$resume_id/': typeof RAuthenticatedSidebarResumesResume_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/r'
    | '/r/dashboard/'
    | '/r/jobs/'
    | '/r/resumes/'
    | '/r/jobs/$job_id/'
    | '/r/resumes/$resume_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/r'
    | '/r/dashboard'
    | '/r/jobs'
    | '/r/resumes'
    | '/r/jobs/$job_id'
    | '/r/resumes/$resume_id'
  id:
    | '__root__'
    | '/'
    | '/r/_authenticated'
    | '/r/_authenticated/_sidebar'
    | '/r/_authenticated/_sidebar/dashboard/'
    | '/r/_authenticated/_sidebar/jobs/'
    | '/r/_authenticated/_sidebar/resumes/'
    | '/r/_authenticated/_sidebar/jobs/$job_id/'
    | '/r/_authenticated/_sidebar/resumes/$resume_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RAuthenticatedRoute: typeof RAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/_authenticated': {
      id: '/r/_authenticated'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/_authenticated/_sidebar': {
      id: '/r/_authenticated/_sidebar'
      path: ''
      fullPath: '/r'
      preLoaderRoute: typeof RAuthenticatedSidebarRouteImport
      parentRoute: typeof RAuthenticatedRoute
    }
    '/r/_authenticated/_sidebar/resumes/': {
      id: '/r/_authenticated/_sidebar/resumes/'
      path: '/resumes'
      fullPath: '/r/resumes/'
      preLoaderRoute: typeof RAuthenticatedSidebarResumesIndexRouteImport
      parentRoute: typeof RAuthenticatedSidebarRoute
    }
    '/r/_authenticated/_sidebar/jobs/': {
      id: '/r/_authenticated/_sidebar/jobs/'
      path: '/jobs'
      fullPath: '/r/jobs/'
      preLoaderRoute: typeof RAuthenticatedSidebarJobsIndexRouteImport
      parentRoute: typeof RAuthenticatedSidebarRoute
    }
    '/r/_authenticated/_sidebar/dashboard/': {
      id: '/r/_authenticated/_sidebar/dashboard/'
      path: '/dashboard'
      fullPath: '/r/dashboard/'
      preLoaderRoute: typeof RAuthenticatedSidebarDashboardIndexRouteImport
      parentRoute: typeof RAuthenticatedSidebarRoute
    }
    '/r/_authenticated/_sidebar/resumes/$resume_id/': {
      id: '/r/_authenticated/_sidebar/resumes/$resume_id/'
      path: '/resumes/$resume_id'
      fullPath: '/r/resumes/$resume_id/'
      preLoaderRoute: typeof RAuthenticatedSidebarResumesResume_idIndexRouteImport
      parentRoute: typeof RAuthenticatedSidebarRoute
    }
    '/r/_authenticated/_sidebar/jobs/$job_id/': {
      id: '/r/_authenticated/_sidebar/jobs/$job_id/'
      path: '/jobs/$job_id'
      fullPath: '/r/jobs/$job_id/'
      preLoaderRoute: typeof RAuthenticatedSidebarJobsJob_idIndexRouteImport
      parentRoute: typeof RAuthenticatedSidebarRoute
    }
  }
}

interface RAuthenticatedSidebarRouteChildren {
  RAuthenticatedSidebarDashboardIndexRoute: typeof RAuthenticatedSidebarDashboardIndexRoute
  RAuthenticatedSidebarJobsIndexRoute: typeof RAuthenticatedSidebarJobsIndexRoute
  RAuthenticatedSidebarResumesIndexRoute: typeof RAuthenticatedSidebarResumesIndexRoute
  RAuthenticatedSidebarJobsJob_idIndexRoute: typeof RAuthenticatedSidebarJobsJob_idIndexRoute
  RAuthenticatedSidebarResumesResume_idIndexRoute: typeof RAuthenticatedSidebarResumesResume_idIndexRoute
}

const RAuthenticatedSidebarRouteChildren: RAuthenticatedSidebarRouteChildren = {
  RAuthenticatedSidebarDashboardIndexRoute:
    RAuthenticatedSidebarDashboardIndexRoute,
  RAuthenticatedSidebarJobsIndexRoute: RAuthenticatedSidebarJobsIndexRoute,
  RAuthenticatedSidebarResumesIndexRoute:
    RAuthenticatedSidebarResumesIndexRoute,
  RAuthenticatedSidebarJobsJob_idIndexRoute:
    RAuthenticatedSidebarJobsJob_idIndexRoute,
  RAuthenticatedSidebarResumesResume_idIndexRoute:
    RAuthenticatedSidebarResumesResume_idIndexRoute,
}

const RAuthenticatedSidebarRouteWithChildren =
  RAuthenticatedSidebarRoute._addFileChildren(
    RAuthenticatedSidebarRouteChildren,
  )

interface RAuthenticatedRouteChildren {
  RAuthenticatedSidebarRoute: typeof RAuthenticatedSidebarRouteWithChildren
}

const RAuthenticatedRouteChildren: RAuthenticatedRouteChildren = {
  RAuthenticatedSidebarRoute: RAuthenticatedSidebarRouteWithChildren,
}

const RAuthenticatedRouteWithChildren = RAuthenticatedRoute._addFileChildren(
  RAuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RAuthenticatedRoute: RAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
